/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExchangeIndexRouteImport } from './routes/exchange/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardNotesRouteImport } from './routes/_authed/dashboard.notes'
import { Route as AuthedDashboardMainRouteImport } from './routes/_authed/dashboard.main'
import { Route as AuthedDashboardRunIdRouteImport } from './routes/_authed/dashboard.run.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeIndexRoute = ExchangeIndexRouteImport.update({
  id: '/exchange/',
  path: '/exchange/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardNotesRoute = AuthedDashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardMainRoute = AuthedDashboardMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardRunIdRoute = AuthedDashboardRunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/exchange': typeof ExchangeIndexRoute
  '/dashboard/main': typeof AuthedDashboardMainRoute
  '/dashboard/notes': typeof AuthedDashboardNotesRoute
  '/dashboard/run/$id': typeof AuthedDashboardRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/exchange': typeof ExchangeIndexRoute
  '/dashboard/main': typeof AuthedDashboardMainRoute
  '/dashboard/notes': typeof AuthedDashboardNotesRoute
  '/dashboard/run/$id': typeof AuthedDashboardRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/exchange/': typeof ExchangeIndexRoute
  '/_authed/dashboard/main': typeof AuthedDashboardMainRoute
  '/_authed/dashboard/notes': typeof AuthedDashboardNotesRoute
  '/_authed/dashboard/run/$id': typeof AuthedDashboardRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/exchange'
    | '/dashboard/main'
    | '/dashboard/notes'
    | '/dashboard/run/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/exchange'
    | '/dashboard/main'
    | '/dashboard/notes'
    | '/dashboard/run/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed/dashboard'
    | '/exchange/'
    | '/_authed/dashboard/main'
    | '/_authed/dashboard/notes'
    | '/_authed/dashboard/run/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  ExchangeIndexRoute: typeof ExchangeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/': {
      id: '/exchange/'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/notes': {
      id: '/_authed/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof AuthedDashboardNotesRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/main': {
      id: '/_authed/dashboard/main'
      path: '/main'
      fullPath: '/dashboard/main'
      preLoaderRoute: typeof AuthedDashboardMainRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/run/$id': {
      id: '/_authed/dashboard/run/$id'
      path: '/run/$id'
      fullPath: '/dashboard/run/$id'
      preLoaderRoute: typeof AuthedDashboardRunIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardMainRoute: typeof AuthedDashboardMainRoute
  AuthedDashboardNotesRoute: typeof AuthedDashboardNotesRoute
  AuthedDashboardRunIdRoute: typeof AuthedDashboardRunIdRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardMainRoute: AuthedDashboardMainRoute,
  AuthedDashboardNotesRoute: AuthedDashboardNotesRoute,
  AuthedDashboardRunIdRoute: AuthedDashboardRunIdRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  ExchangeIndexRoute: ExchangeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
