/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExchangeIndexRouteImport } from './routes/exchange/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardChartsRouteImport } from './routes/_authed/dashboard._charts'
import { Route as AuthedDashboardChartsIndexRouteImport } from './routes/_authed/dashboard._charts.index'
import { Route as AuthedDashboardRunIdRouteImport } from './routes/_authed/dashboard.run.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeIndexRoute = ExchangeIndexRouteImport.update({
  id: '/exchange/',
  path: '/exchange/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardChartsRoute = AuthedDashboardChartsRouteImport.update({
  id: '/_charts',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardChartsIndexRoute =
  AuthedDashboardChartsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardChartsRoute,
  } as any)
const AuthedDashboardRunIdRoute = AuthedDashboardRunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardChartsRouteWithChildren
  '/exchange': typeof ExchangeIndexRoute
  '/dashboard/run/$id': typeof AuthedDashboardRunIdRoute
  '/dashboard/': typeof AuthedDashboardChartsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardChartsIndexRoute
  '/exchange': typeof ExchangeIndexRoute
  '/dashboard/run/$id': typeof AuthedDashboardRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/exchange/': typeof ExchangeIndexRoute
  '/_authed/dashboard/_charts': typeof AuthedDashboardChartsRouteWithChildren
  '/_authed/dashboard/run/$id': typeof AuthedDashboardRunIdRoute
  '/_authed/dashboard/_charts/': typeof AuthedDashboardChartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/exchange'
    | '/dashboard/run/$id'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/exchange' | '/dashboard/run/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed/dashboard'
    | '/exchange/'
    | '/_authed/dashboard/_charts'
    | '/_authed/dashboard/run/$id'
    | '/_authed/dashboard/_charts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  ExchangeIndexRoute: typeof ExchangeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/': {
      id: '/exchange/'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/_charts': {
      id: '/_authed/dashboard/_charts'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardChartsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/_charts/': {
      id: '/_authed/dashboard/_charts/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardChartsIndexRouteImport
      parentRoute: typeof AuthedDashboardChartsRoute
    }
    '/_authed/dashboard/run/$id': {
      id: '/_authed/dashboard/run/$id'
      path: '/run/$id'
      fullPath: '/dashboard/run/$id'
      preLoaderRoute: typeof AuthedDashboardRunIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardChartsRouteChildren {
  AuthedDashboardChartsIndexRoute: typeof AuthedDashboardChartsIndexRoute
}

const AuthedDashboardChartsRouteChildren: AuthedDashboardChartsRouteChildren = {
  AuthedDashboardChartsIndexRoute: AuthedDashboardChartsIndexRoute,
}

const AuthedDashboardChartsRouteWithChildren =
  AuthedDashboardChartsRoute._addFileChildren(
    AuthedDashboardChartsRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardChartsRoute: typeof AuthedDashboardChartsRouteWithChildren
  AuthedDashboardRunIdRoute: typeof AuthedDashboardRunIdRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardChartsRoute: AuthedDashboardChartsRouteWithChildren,
  AuthedDashboardRunIdRoute: AuthedDashboardRunIdRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  ExchangeIndexRoute: ExchangeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
